language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pep517
- pip install .
- pip install codecov
script:
- pytest
after_success:
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: W+XH11XR0bP2t8dE4aPcXUgsxRQIxMKHNzKKXyvGOq6AL4mZdK7EnB3433yNviBvGzZdKnShXDP3gULgWbRRh6g5Vv7x9R3DxE82+2beTJMrk7LmiwBRAprz7dvMBJN5fAJdFd6RFwLWqtMYbFoiSCSwdFq03iYvxFfliY2didzmPOAwNU4bpbaXQb2RndwwUZBv7OXVrOjPwbCJ3PWK0RvUDsmJ1YSWFS6mP1WzFcdI565sXIpRwXeXcs++qjWvCciL+vjjYeDyrCRXgNvyPhXX4d+NNhOQ+MK2yVNwsvzCEB0c+RDiOt/XJwM/S0aIzwjbu9pSNvE95XyieHa3ag60IQrqpf1ZPEhGcOBnac+dS6FnpRDyQkxTK4kCGbqLWKZ11tkXARYe+3e7HxGLffTlfodvkcp8xYT1B9M50VG3u2SB0oP7IaUIjj1Tcrch63yulVzM3fF+L+dXjmndgzwLna1REwaBpDLHjqp3HtDXSJ9SH/PFjrlRKehLYfRcpYB4KmWFLXkATaGgtXzUHQYm80c1HUMH7zDQZz/LddmILz/RW37DkmqqlmlfoXmTyYK5I9Ji3tnfFF7d3pjWGMGGTVkraPFtHYJ7++DzDukMe/d7c93defLhCRfPzdh2gnSgbjhra0I/4S60YObiB6xNY4enky5nct4eWIcmXCE=
  on:
    tags: true
  skip_existing: true
